package com.acltabontabon.modscope.scan;

public enum FileCategory {
    GAME_EXECUTABLE,
    RUNTIME_LIBRARY,
    NVIDIA_LIBRARY,
    STEAM_LIBRARY,
    GRAPHICS_LIBRARY,
    STREAMLINE_LIBRARY,
    PHYSX_LIBRARY,
    DIRECTSTORAGE_LIBRARY,
    SYSTEM_COMPAT_LIBRARY,
    VENDOR_LIBRARY,
    ARCHIVE,
    PACKAGE_DEFINITION,
    CONFIG,
    TEXT,
    VIDEO,
    LOCALIZATION,
    SHADER_CACHE,
    UNKNOWN_LARGE,
    OTHER
}
